# Generated by Django 2.2.1 on 2019-05-10 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileListBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=255)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_title', models.CharField(max_length=20)),
                ('file_size', models.FloatField(blank=True, default=0, null=True)),
                ('document', models.FileField(max_length=1500, upload_to='documents/')),
                ('t_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('num', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('subject_num', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_num', models.IntegerField(null=True)),
                ('subject_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Subject')),
                ('team_num', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('roomName', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
