# Generated by Django 2.0.2 on 2019-04-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InviteBox',
        ),
        migrations.DeleteModel(
            name='NotificationBox',
        ),
        migrations.DeleteModel(
            name='ReviewBox',
        ),
        migrations.DeleteModel(
            name='TaskBox',
        ),
        migrations.RemoveField(
            model_name='filelistbox',
            name='assignment_title',
        ),
        migrations.RemoveField(
            model_name='filelistbox',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='filelistbox',
            name='deadline_date',
        ),
        migrations.RemoveField(
            model_name='filelistbox',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='filelistbox',
            name='weights_num',
        ),
    ]
