# Generated by Django 2.1.7 on 2019-05-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='documents',
            field=models.FileField(max_length=1500, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='post',
            name='file_name',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
