# Generated by Django 2.2.1 on 2019-05-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190430_1841'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
