# Generated by Django 2.1.7 on 2019-04-16 06:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team_doc_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileListBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(max_length=255)),
                ('class_name', models.CharField(max_length=20)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('team_title', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=10)),
                ('weights_num', models.FloatField(blank=True, default=1200.0, null=True)),
                ('assignment_title', models.CharField(blank=True, max_length=20)),
                ('deadline_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.FloatField(blank=True, default=0, null=True)),
                ('document', models.FileField(max_length=1500, upload_to='documents/')),
                ('t_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InviteBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=10)),
                ('class_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_filename', models.TextField(max_length=255)),
                ('uploaded_account', models.CharField(max_length=10)),
                ('uploaded_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploaded_teamtitle', models.CharField(max_length=20)),
                ('edited_orwhat', models.BooleanField(default=False)),
                ('read_ox', models.BooleanField(default=False)),
                ('uploaded_groupid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='subject_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='team_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Team'),
        ),
    ]
