# Generated by Django 2.1.7 on 2019-04-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190416_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='userid',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
