# Generated by Django 2.1.7 on 2019-04-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_subject_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_dead', models.DateTimeField()),
                ('credit_per_two', models.FloatField(blank=True, default=0.3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_file', models.TextField(max_length=255)),
                ('review_uploader', models.CharField(max_length=10)),
                ('review_subject', models.CharField(max_length=20)),
                ('review_team', models.IntegerField(default=0)),
                ('review_er', models.CharField(max_length=20)),
                ('review_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_review_score', models.IntegerField(default=0)),
                ('credit_per_three', models.FloatField(blank=True, default=0.35, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_role', models.CharField(max_length=10)),
                ('credit_per', models.FloatField(blank=True, default=0.1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_user', models.CharField(max_length=20)),
                ('task_role', models.CharField(max_length=10)),
                ('task_status', models.CharField(max_length=10)),
                ('task_percent', models.IntegerField(default=0)),
                ('task_dead', models.DateTimeField()),
                ('task_subject', models.CharField(max_length=20)),
                ('task_team', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamHistoryCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_user', models.CharField(max_length=20)),
                ('th_count_of_history', models.FloatField(blank=True, default=0.0, null=True)),
                ('th_credit', models.FloatField(blank=True, default=0.15, null=True)),
            ],
        ),
    ]
