# Generated by Django 2.1.7 on 2019-04-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_deadcredit_reviewbox_reviewcredit_rolecredit_taskbox_teamhistorycredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbox',
            name='task_dead',
            field=models.CharField(max_length=20),
        ),
    ]
