# Generated by Django 2.1.7 on 2019-04-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190421_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewbox',
            name='review_comments',
            field=models.TextField(blank=True, default='의견 없음', max_length=255),
        ),
    ]
