# Generated by Django 2.1.7 on 2019-04-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190423_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewbox',
            name='review_comments',
            field=models.CharField(blank=True, default='의견 없음', max_length=255),
        ),
        migrations.AlterField(
            model_name='reviewbox',
            name='review_file',
            field=models.CharField(max_length=255),
        ),
    ]
